# Generated by Django 2.2.4 on 2019-10-11 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Desc', models.TextField()),
                ('Completed', models.BooleanField(default=False)),
                ('Enrollment_ID', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
