# Generated by Django 2.2.4 on 2019-10-11 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Desc', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='Date_of_Publishing',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
