# Generated by Django 2.2.4 on 2019-10-11 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0003_course_tag_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_Ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.TextField()),
                ('Video_Link', models.URLField()),
                ('DOP', models.DateTimeField(auto_now=True)),
                ('Desc', models.TextField()),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Tutor')),
                ('Course_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Code', models.FileField(upload_to='')),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('Problem_Ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Practice')),
            ],
        ),
        migrations.AddField(
            model_name='practice',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Tutor'),
        ),
        migrations.AddField(
            model_name='practice',
            name='Lec_Ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Video'),
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.TextField()),
                ('Ref_Link', models.URLField()),
                ('Tag_ID', models.ManyToManyField(to='courses.Tag')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='Author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='courses.Tutor'),
            preserve_default=False,
        ),
    ]
