# Generated by Django 2.2.4 on 2019-12-07 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_auto_20191207_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.Tutor'),
        ),
    ]
