# Generated by Django 2.2.4 on 2019-12-07 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20191207_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.Tutor'),
        ),
        migrations.AlterField(
            model_name='video',
            name='Course_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='courses.Course'),
        ),
    ]
